### ISSUE TITLE
Hardcoded tests

### ISSUE THREAD

**Issue by jaanos** [MitjaR/SATsolverLVR#1]
Your program makes some function calls with hardcoded file names, which makes it impossible to run it on another file without running the tests first (also, the files may not exist in the current path, causing the program to fail before anything is run). Please provide a way to run it on an arbitrary file.

Please see my [attempt](https://github.com/jaanos/LVR-2016/blob/master/hw-satsolver/run/run-pythonsolver.py) at calling your program (which doesn't work due to the reason given above).

**Comment by MitjaR** [comment]
Sem popravil. Sedaj se ob zagonu programa ne naredi nič. Proste ukaze sem zapakiral v funkcijo **main**(). Vaš klic SATsolvePopravljen.SATsolverDimacs(sys.argv[1], sys.argv[2]) je pravilen. 
Pri tem je prvi argument funkcije niz vhodne datoteke, drugi argument pa niz izhodne.

**Comment by jaanos** [comment]
V redu, hvala.
